pipeline{
    agent any
    environment {
        DOCKER_CREDENTIALS = credentials('Docker')
    }
    stages{
        stage('Checkout'){
            steps{
                git 'https://github.com/Aridoshikaju/Employee-Management-Nginx-Load_balanced.git'
            }
        }
        stage('Building Container'){
            steps{
                dir('App/node_server'){
                    docker.build("aridoshikaju/employee_management:latest")
                }
            }
        }
        stage('Pushing to docker hub'){
            steps{
                script{
                    docker.withRegistry('https://registry.hub.docker.com', DOCKER_CREDENTIALS) {
                        docker.image("aridoshikaju/employee_management:latest").push()
                    }
                }
            }
        }
    }
}